name: Env Variables Demo

on: workflow_dispatch

env:
  GLOBAL_ENV: "global-value"

jobs:
  demo:
    runs-on: ubuntu-latest
    
    environment: production

    steps:
      - name: use env vars
        run: |
          echo "API URL: $API_URL"
          echo "APP MODE: $APP_MODE"